### PR TITLE
refactor: store protobuf messages in corresponding tables

### PR DESCRIPTION
**Pull request by jhoward-lm**
This PR stores protobom message data in the associated ent schema tables. It also generates deterministic UUIDs from a hash of the wire format message to use as primary keys.

All changes in this PR are auto-generated except the files in `backends/ent/` and `internal/backends/ent/schema/`.

### CODE REVIEW

**Review by puerco — COMMENTED** [review]
Some of these functions really needs some tests to ensure consistency, are you planning to add some as part of this PR? There is a high risk of data corruption if we merge a bug in of these.

**Comment by puerco** [comment]
Oh, thank I was just thinking ahead, not necessarily for now, but it's cool you pushed them :)

**Comment by jhoward-lm** [comment]
@ashearin @pkwiatkowski1 @lmphil

Can you guys take a look at the changes in `internal/backends/ent/schema/`?

Looking to see if the new fields make sense (i.e. storing the proto messages as an additional field alongside their corresponding ent schemas), or if there might be a better way to do it.

**Comment by ashearin** [comment]
> Can you guys take a look at the changes in `internal/backends/ent/schema/`?
> 
> Looking to see if the new fields make sense (i.e. storing the proto messages as an additional field alongside their corresponding ent schemas), or if there might be a better way to do it.

@jhoward-lm  From what I understand (and looked up just now) about ent schemas and mixins, what you're doing makes sense.

**Review by puerco — APPROVED** [review]
All right, looks like it is ready to go. Amazing work :rocket:

**Pull request merged**
